version: '3.8'
services:
  postgres:
    image: postgres
    container_name: airplane-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: airplane
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend


volumes:
  postgres_data:

networks:
  backend: